apiVersion: apps/v1
kind: Deployment
metadata:
  name: veaas-worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: veaas-worker
  template:
    metadata:
      labels:
        app: veaas-worker
    spec:
      containers:
      - name: veaas-worker
        image: cvarad/veaas-worker
        # resources:
        #   requests:
        #     cpu: 1000m
        #     memory: 2048Mi
        env:
          - name: MINIO_HOST
            value: "minio:9000"
          - name: NATS_HOST
            value: "my-nats"
